version: 2.1
workflows:
  build:
    jobs:
      - foo
      - bar:
          requires:
            - foo
jobs:
  foo:
    docker:
      - image: alpine:3.13.1
    steps:
      - run:
          name: foo
          command: |
            pwd
            apk add git openssh
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .circleci
  bar:
    docker:
      - image: alpine:3.13.1
    steps:
      - run:
          name: bar
          command: |
            apk add ca-certificates tree
            mkdir /tmp/workspace
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: bar
          command: |
            tree -a /tmp/workspace
