version: 2.1

orbs:
  aqua: aquaproj/aqua@dev:pr-359

workflows:
  build:
    jobs:
      - foo
jobs:
  foo:
    docker:
      - image: alpine:3.18.2
    steps:
      - run:
          command: |
            apk add git curl bash
      - checkout
      - aqua/aqua:
          aqua_version: v2.9.1
      - aqua/update-checksum
