version: 2.1

orbs:
  aqua: aquaproj/aqua@0.3.1

workflows:
  build:
    jobs:
      - foo
jobs:
  foo:
    docker:
      - image: debian:12.0
    steps:
      - run:
          command: |
            apt update -y
            apt install -y git curl
      - checkout
      - aqua/aqua:
          aqua_version: v2.10.0
      - aqua/update-checksum
