version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@1.0.1
workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: alpine:3.10.3
    steps:
      - git-shallow-clone
