version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: test shell
          shell: grep hello
          command: |
            hello
            foo
