version: 2.1

orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.0

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: plugins/git
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: '--shallow-since "1 years ago"'
          fetch_options: '--shallow-since "1 years ago"'
