version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: plugins/git
    steps:
      - checkout
      - run:
          name: check the SHA1 of master
          command: |
            git show-branch master
            git show-branch origin/master
