version: 2.1

orbs:
  aqua: aquaproj/aqua@dev:c72fb3e0c46bb921f9bc9922b1b32df13667b30f

workflows:
  build:
    jobs:
      - foo
jobs:
  foo:
    docker:
      - image: alpine:3.18.2
    steps:
      - run:
          command: |
            apk add git curl
      - checkout
      - aqua/aqua:
          aqua_version: v2.9.0
      - run:
          command: |
            command -v circleci
            circleci version
