version: 2.1
workflows:
  build:
    jobs:
      - foo
      - bar
      - foo:
          requires:
            - bar
jobs:
  foo:
    docker:
      - image: alpine:3.13.1
    steps:
      - run:
          name: foo
          command: |
            pwd
            apk add git
      - checkout
  bar:
    docker:
      - image: alpine:3.13.1
    steps:
      - run:
          name: bar
          command: echo bar
