---
jobs:
  setup:
    docker:
      - image: alpine:3.10.3
    steps:
      - checkout
      - run: |
          sleep 3
          echo build
  test:
    docker:
      - image: alpine:3.10.3
    steps:
      - run: |
          sleep 5
          echo test
workflows:
  version: 2
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
