version: 2.1
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build:
          name: release
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
jobs:
  build:
    docker:
      - image: golang:1.14.0
    steps:
      - checkout
      - run:
          command: go run main.go
