version: 2.1

orbs:
  aqua: aquaproj/aqua@dev:2e23d12a895d5cda59ce4d1f9081d70c0f336e90

workflows:
  build:
    jobs:
      - foo
jobs:
  foo:
    docker:
      - image: alpine:3.18.2
    steps:
      - run:
          command: |
            apk add git curl bash
      - checkout
      - aqua/aqua:
          aqua_version: v2.25.0
          aqua_log_level: debug
          aqua_config: aqua.yaml
          aqua_only_link: false
          aqua_all: true
          aqua_exclude_tags: foo,bar
      - run:
          shell: /bin/bash -euo pipefail
          command: |
            command -v circleci
            circleci version
