version: 2.1

workflows:
  build:
    jobs:
      - hello
jobs:
  hello:
    docker:
      - image: alpine:3.11.3
    steps:
      - run:
          command: |
            echo_error() {
              COLOR_1="\e[31;1m"
              COLOR_OFF="\e[m"
              echo -e "${COLOR_1}$*${COLOR_OFF}" >&2
            }
            echo_error hello
