version: 2.1

orbs:
  aqua: aquaproj/aqua@dev:pr-354

workflows:
  build:
    jobs:
      - foo
jobs:
  foo:
    docker:
      - image: alpine:3.18.2
    steps:
      - run:
          command: |
            apk add git curl bash
      - checkout
      - aqua/aqua:
          aqua_version: v2.9.0
      - run:
          shell: /bin/bash -euo pipefail
          command: |
            command -v circleci
            circleci version
