version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: ignore failure
          # shell: /bin/sh || true
          shell: /bin/sh -c "sh || true"
          command: |
            echo start
            false
            echo end
