version: 2.1

workflows:
  build:
    jobs:
      - foo
      - bar
      - foo:
          requires:
            - bar
jobs:
  foo:
    docker:
      - image: alpine:3.18.2
    steps:
      - run:
          name: foo
          command: echo foo
  bar:
    docker:
      - image: alpine:3.18.2
    steps:
      - run:
          name: bar
          command: echo bar
