version: 2.1

orbs:
  # aqua: suzuki-shunsuke/aqua@dev:pr-2
  aqua: aquaproj/aqua@dev:pr-5

workflows:
  build:
    jobs:
      - foo:
          context: suzuki-shunsuke
      - bar:
          context: suzuki-shunsuke
          requires:
            - foo
commands:
  aqua:
    steps:
      - aqua/install-aqua:
          version: v0.7.16 # renovate: depName=suzuki-shunsuke/aqua
      - aqua/aqua-install:
          aqua_root_dir: /root/.aqua
  set_aqua_env:
    steps:
      - run:
          shell: bash -eo pipefail
          command: echo 'export "PATH=/root/.aqua/bin:$PATH"' >> $BASH_ENV
jobs:
  foo:
    docker:
      - image: alpine:3.14.2
    steps:
      - run:
          command: apk add git bash curl
      - checkout
      - aqua
      - set_aqua_env
      - run:
          shell: bash -eo pipefail
          command: github-comment -v

  bar:
    docker:
      - image: alpine:3.14.2
    steps:
      - run:
          command: apk add git bash curl
      - checkout
      - aqua
      - set_aqua_env
      - run:
          shell: bash -eo pipefail
          command: github-comment -v
