version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@1.2.2

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: plugins/git
    steps:
      - git-shallow-clone/checkout_shallow:
          clone_options: '--shallow-since "1 years ago"'
