version: 2.1

orbs:
  aqua: suzuki-shunsuke/aqua@dev:pr-2

workflows:
  build:
    jobs:
      - foo:
          context: suzuki-shunsuke
      - bar:
          context: suzuki-shunsuke
          requires:
            - foo
commands:
  aqua:
    steps:
      - aqua/install-aqua:
          version: v0.7.6 # renovate: depName=suzuki-shunsuke/aqua
      - aqua/aqua-install:
          aqua_root_dir: /root/.aqua
jobs:
  foo:
    docker:
      - image: alpine:3.14.2
    steps:
      - run:
          command: apk add git bash curl
      - checkout
      - aqua
      - run:
          command: github-comment -v

  bar:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          command: apk add git bash curl
      - checkout
      - aqua
      - run:
          command: github-comment -v
