version: 2.1

workflows:
  build:
    jobs:
      - build
      - build2:
          requires:
            - build
jobs:
  build:
    docker:
      - image: alpine:3.12.0
    steps:
      - run:
          command: "false"
  build2:
    docker:
      - image: alpine:3.12.0
    steps:
      - run:
          command: "false"
      - run:
          command: echo world
          when: on_fail
