version: 2.1

workflows:
  build:
    jobs:
      - foo
jobs:
  foo:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: foo
          command: |
            apk add git openssh
      - checkout
      - run:
          name: foo
          command: |
            git fetch --depth 1 origin "pull/16/merge:pr/16/merge"
            git checkout "pr/16/merge"
            git rev-parse HEAD
