version: 2.1

workflows:
  build:
    jobs:
      - foo:
          filters:
            branches:
              ignore:
                - /(?<!foo)/master/
jobs:
  foo:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: foo
          command: echo foo
