version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: alpine:3.11.6
    steps:
      - run:
          name: install shell-ignore-failure
          command: |
            echo "#!/bin/sh" > /usr/local/bin/shell-ignore-failure
            echo 'cat - | sh' >> /usr/local/bin/shell-ignore-failure
            echo ':' >> /usr/local/bin/shell-ignore-failure
            cat /usr/local/bin/shell-ignore-failure
            chmod +x /usr/local/bin/shell-ignore-failure
      - run:
          name: ignore failure
          shell: /usr/local/bin/shell-ignore-failure
          command: >
            echo start
            false
            echo end
